# Generated by Django 5.2 on 2025-04-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviedata',
            options={'verbose_name_plural': 'Movie data'},
        ),
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='movie_images/default.jpg', upload_to='movie_images/'),
        ),
    ]
